### ISSUE TITLE
Does'nt support adding of css in direct ES6 import

### ISSUE THREAD

**Issue by kevde** [stoikerty/dev-toolkit#30]
![one](https://cloud.githubusercontent.com/assets/13955467/19728880/aa92a860-9bc7-11e6-943a-a84d11848b6a.PNG)
![two](https://cloud.githubusercontent.com/assets/13955467/19728882/abe04f38-9bc7-11e6-97ea-e4862670ae3c.PNG)

**Comment by stoikerty** [comment]
That's right, there is no support for css-imports right now. You can still import them separately by adding the css-file you need to your public-files folder and then importing that in your template `layout.hbs`.

This way you're also putting less strain on the compiler since that min-file is potentially quite large and does not need any processing. I'm not entirely sure it's a good idea to add support for css-imports because of potential issues like these.

**Comment by stoikerty** [comment]
I've [added the ability to import css-files](https://github.com/stoikerty/dev-toolkit/pull/33). This won't give you the ability to import css into the javascript directly (this isn't part of css-modules), but it will allow you to add separate `.css`-files with css-modules and autoprefixer support if you don't want to use `.scss`. You can still add full css-files via the `public-files`-folder as before.
